In [5]:
import pandas as pd

s1 = pd.Series({'Name': 'ana', 'Score':9})
s2 = pd.Series({'Name': 'ceci', 'Score':8})

df = pd.DataFrame([s1, s2], index =['student1', 'student2'])

df

          Name  Score
student1   ana      9
student2  ceci      8

In [6]:
df['Name']
print(type(df['Name']))

<class 'pandas.core.series.Series'>

In [7]:
df.loc['student1']
print(type(df.loc['student1']))

<class 'pandas.core.series.Series'>

In [8]:
df = pd.read_csv('NISPUF17.csv')
df.head()

,Unnamed: 0,SEQNUMC,SEQNUMHH,PDAT,PROVWT_D,RDDWT_D,STRATUM,YEAR,AGECPOXR,HAD_CPOX,...,XVRCTY2,XVRCTY3,XVRCTY4,XVRCTY5,XVRCTY6,XVRCTY7,XVRCTY8,XVRCTY9,INS_STAT2_I,INS_BREAK_I
0,1,128521,12852,2,NaN,235.916956,1031,2017,NaN,2,...,,,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,2,10741,1074,2,NaN,957.353840,1068,2017,NaN,2,...,,,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2,3,220011,22001,2,NaN,189.611299,1050,2017,NaN,2,...,,,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3,4,86131,8613,1,675.430817,333.447418,1040,2017,NaN,2,...,,,NaN,NaN,NaN,NaN,NaN,NaN,1.0,2.0
4,5,227141,22714,1,482.617748,278.768063,1008,2017,NaN,2,...,,,NaN,NaN,NaN,NaN,NaN,NaN,2.0,1.0

In [9]:
df.columns

Index(['Unnamed: 0', 'SEQNUMC', 'SEQNUMHH', 'PDAT', 'PROVWT_D', 'RDDWT_D',
       'STRATUM', 'YEAR', 'AGECPOXR', 'HAD_CPOX',
       ...
       'XVRCTY2', 'XVRCTY3', 'XVRCTY4', 'XVRCTY5', 'XVRCTY6', 'XVRCTY7',
       'XVRCTY8', 'XVRCTY9', 'INS_STAT2_I', 'INS_BREAK_I'],
      dtype='object', length=454)

In [10]:
columns_to_keep = ['EDUC1']
df = df[columns_to_keep]
df.head()

   EDUC1
0      4
1      3
2      3
3      4
4      1

In [11]:
edu_mask = df['EDUC1'] == 12

#df.where(edu_mask).dropna().head()
len(df[df['EDUC1'] == 2])/len(df)

0.17966101694915254

In [12]:
df[df['EDUC1'] > 12]

Empty DataFrame
Columns: [EDUC1]
Index: []

In [13]:
def proportion_of_education():
    # your code goes here
    # YOUR CODE HERE
    #raise NotImplementedError()


    dic = {"less than high school":len(df[df['EDUC1'] == 1])/len(df),
    "high school":len(df[df['EDUC1'] == 2])/len(df),
    "more than high school but not college":len(df[df['EDUC1'] == 3])/len(df),
    "college":len(df[df['EDUC1'] == 4])/len(df)}
 
    return dic

In [14]:
def average_influenza_doses():
    # YOUR CODE HERE
    raise NotImplementedError()

In [15]:
df = pd.read_csv('NISPUF17.csv')
df.head()

,Unnamed: 0,SEQNUMC,SEQNUMHH,PDAT,PROVWT_D,RDDWT_D,STRATUM,YEAR,AGECPOXR,HAD_CPOX,...,XVRCTY2,XVRCTY3,XVRCTY4,XVRCTY5,XVRCTY6,XVRCTY7,XVRCTY8,XVRCTY9,INS_STAT2_I,INS_BREAK_I
0,1,128521,12852,2,NaN,235.916956,1031,2017,NaN,2,...,,,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,2,10741,1074,2,NaN,957.353840,1068,2017,NaN,2,...,,,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2,3,220011,22001,2,NaN,189.611299,1050,2017,NaN,2,...,,,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3,4,86131,8613,1,675.430817,333.447418,1040,2017,NaN,2,...,,,NaN,NaN,NaN,NaN,NaN,NaN,1.0,2.0
4,5,227141,22714,1,482.617748,278.768063,1008,2017,NaN,2,...,,,NaN,NaN,NaN,NaN,NaN,NaN,2.0,1.0

CBF_01 – child ever fed breast milk yes 1, no 2
P_NUMFLU – total number of seasonal influenza doses

In [31]:
import pandas as pd
import numpy as np
df = pd.read_csv('NISPUF17.csv')
columns_to_keep = ['CBF_01', 'P_NUMFLU' ]

df = df[columns_to_keep]
#df.isna().sum() #NaN values
df=df[df['P_NUMFLU'].notna()]
tot1 = len(df[df['CBF_01']==1])
tot2 = len(df[df['CBF_01']==2])
mi=df[df['CBF_01']==1]['P_NUMFLU'].sum()
notmi=df[df['CBF_01']==2]['P_NUMFLU'].sum()
#return (mi/tot1, notmi/tot2)
print(mi/tot1, notmi/tot2)
#df = df.dropna()

# df = df[(df['CBF_01'] != 77) & (df['CBF_01'] != 99)]
# print(df['CBF_01'].unique())


# print('total: ', len(df))

# yes_df = df[df['CBF_01'] == 1]
# no_df = df[df['CBF_01'] == 2]

# print('yes: ', len(yes_df))
# print('no: ', len(no_df))

# sum_yes =np.sum(yes_df['P_NUMFLU'])
# sum_no =np.sum(no_df['P_NUMFLU'])

# avg_yes = sum_yes/len(yes_df)
# avg_no = sum_no/len(no_df)

# print('avg yes: ', avg_yes)
# print('avg no: ', avg_no)


#np.sum(df[df['CBF_01'] == 1]['P_NUMFLU'])/len(df[df['CBF_01'] == 1)

1.8799187420058687 1.5963945918878317

## Question 3

It would be interesting to see if there is any evidence of a link between vaccine effectiveness and sex of the child. Calculate the ratio of the number of children who contracted chickenpox but were vaccinated against it (at least one varicella dose) versus those who were vaccinated but did not contract chicken pox. Return results by sex.
This function should return a dictionary in the form of (use the correct numbers):
    {"male":0.2,
    "female":0.4}
Note: To aid in verification, the chickenpox_by_sex()['female'] value the autograder is looking for starts with the digits 0.0077.

- HAD_CPOX: kid has had chickenpox. yes = 1, no = 2
- P_NUMVRC – total number of varicella doses
- SEX, male = 1, female = 2

How many girls were vaccinated / How many girls that were vaccinated, had chickpox

In [26]:
import pandas as pd
df = pd.read_csv('NISPUF17.csv')

df = df[df['P_NUMVRC'] >= 1]
yes_CPOX = df[df['HAD_CPOX'] == 1]
no_CPOX  = df[df['HAD_CPOX'] == 2]

male_infected   = len(yes_CPOX[yes_CPOX['SEX'] ==1])
female_infected = len(yes_CPOX[yes_CPOX['SEX'] ==2])

male_no_infected   = len(no_CPOX[no_CPOX['SEX'] ==1])
female_no_infected = len(no_CPOX[no_CPOX['SEX'] ==2])



ratio = {"male":male_infected/male_no_infected,
    "female":female_infected/female_no_infected}
print(ratio)

{'male': 0.009675583380762664, 'female': 0.0077918259335489565}